apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  labels: # Not needed, but good for "clean" docs
    app: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi