apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - name: http
              containerPort: 8123
          env:
            - name: TZ
              value: Asia/Seoul
          volumeMounts:
            - name: config
              mountPath: /config
          startupProbe:
            tcpSocket:
              port: 8123
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            tcpSocket:
              port: 8123
            periodSeconds: 30
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config
